services:
  - name: client
    env: production
    buildCommand: npm run build
    startCommand: npm run start
    github:
      branch: main
      autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: "production"
    plan: starter

  - name: server
    env: production
    buildCommand: npm run build
    startCommand: npm run start
    github:
      branch: main
      autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: "production"
    plan: starter
