build:
  - name: Install dependencies and build client
    command: cd client && npm install && npm run build
    env:
      - name: NODE_ENV
        value: production
  - name: Install dependencies for server
    command: cd server && npm install
    env:
      - name: NODE_ENV
        value: production

start:
  command: npm run start
  env:
    - name: NODE_ENV
      value: production
